// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteWith.Persistence.NoteDataContexts;

#nullable disable

namespace NoteWith.Persistence.Migrations
{
    [DbContext(typeof(NoteDataContext))]
    partial class NoteDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEvent", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("WorkEvents");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEventExcludedUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<Guid>("EventID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("EventID1");

                    b.HasIndex("UserID1");

                    b.ToTable("WorkEventExcludedUsers");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEventGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<Guid>("EventID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("EventID1");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("WorkEventGroups");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEventNotifiedMe", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<Guid>("EventID1")
                        .HasColumnType("char(36)");

                    b.Property<string>("NotificatonID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("EventID1");

                    b.HasIndex("UserID1");

                    b.ToTable("WorkEventNotifiedMes");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GroupFirebaseConnctionID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("WorkGroups");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroupUsers", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsManager")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IsNute")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UserID1");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("WorkGroupUsers");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.MessageModels.PersonelMessageModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverID")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiverID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<Guid>("SenderID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ReceiverID1");

                    b.HasIndex("SenderID1");

                    b.ToTable("PersonelMessageModels");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.MessageModels.WorkGroupMessage", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("SenderID")
                        .HasColumnType("int");

                    b.Property<Guid>("SenderID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("SenderID1");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("WorkGroupMessages");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.Note", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.NoteExcludedUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<int>("NoteID")
                        .HasColumnType("int");

                    b.Property<Guid>("NoteID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("NoteID1");

                    b.HasIndex("UserID1");

                    b.ToTable("NoteExcludedUsers");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.NoteGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoteID")
                        .HasColumnType("int");

                    b.Property<Guid>("NoteID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("NoteID1");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("NoteGroups");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.NoteNotifiedMe", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoteID")
                        .HasColumnType("int");

                    b.Property<Guid>("NoteID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("NoteID1");

                    b.HasIndex("UserID1");

                    b.ToTable("NoteNotifiedMes");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoticeModels.Notice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoticeModels.NoticeSeenUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoticeID")
                        .HasColumnType("int");

                    b.Property<Guid>("NoticeID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("NoticeID1");

                    b.HasIndex("UserID1");

                    b.ToTable("NoticeSeenUsers");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoticeModels.WorkGroupNotice", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NoticeID")
                        .HasColumnType("int");

                    b.Property<Guid>("NoticeID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("NoticeID1");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("WorkGroupNotices");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.UserModels.UserModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailConfirmeToken")
                        .HasColumnType("longtext");

                    b.Property<string>("FireBaseConnectionID")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkFilesFolderID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkFilesFolderID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("WorkFilesFolderID1");

                    b.ToTable("WorkFiles");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkFilesFolder", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("WorkFilesFolders");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkGroupAlbum", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("WorkGroupID1");

                    b.ToTable("WorkGroupAlbums");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkPhoto", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<Guid>("AlbumID1")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UrlMediumImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlOrgin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UrlSmallImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID1");

                    b.ToTable("WorkPhotos");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.ListWorkGroup", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkGroupID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkGroupID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkListID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkListID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("WorkGroupID1");

                    b.HasIndex("WorkListID1");

                    b.ToTable("ListWorkGroups");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkList", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.ToTable("WorkLists");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkListExcludedUser", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkListID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkListID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UserID1");

                    b.HasIndex("WorkListID1");

                    b.ToTable("WorkListExcludedUsers");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkListItem", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<int>("ComplaterUserID")
                        .HasColumnType("int");

                    b.Property<Guid>("ComplaterUserID1")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCoplated")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WorkListID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkListID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("ComplaterUserID1");

                    b.HasIndex("WorkListID1");

                    b.ToTable("WorkListItems");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkListNotifiedMe", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CreadedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreadedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ObjectStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID1")
                        .HasColumnType("char(36)");

                    b.Property<int>("WorkListID")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkListID1")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("UserID1");

                    b.HasIndex("WorkListID1");

                    b.ToTable("WorkListNotifiedMes");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEventExcludedUser", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.EventModels.WorkEvent", "Event")
                        .WithMany("ExcludedUsers")
                        .HasForeignKey("EventID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEventGroup", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.EventModels.WorkEvent", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("EventGroups")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEventNotifiedMe", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.EventModels.WorkEvent", "Event")
                        .WithMany("NotifiedMes")
                        .HasForeignKey("EventID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroupUsers", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany("WorkGroupUsers")
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("WorkGroupUsers")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.MessageModels.PersonelMessageModel", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.MessageModels.WorkGroupMessage", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("Messages")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.NoteExcludedUser", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.NoteModels.Note", "Note")
                        .WithMany("ExcludedUsers")
                        .HasForeignKey("NoteID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.NoteGroup", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.NoteModels.Note", "Note")
                        .WithMany("NoteGroups")
                        .HasForeignKey("NoteID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("NoteGroups")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.NoteNotifiedMe", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.NoteModels.Note", "Note")
                        .WithMany("Notifieds")
                        .HasForeignKey("NoteID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoticeModels.NoticeSeenUser", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.NoticeModels.Notice", "Notice")
                        .WithMany("SeenUsers")
                        .HasForeignKey("NoticeID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoticeModels.WorkGroupNotice", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.NoticeModels.Notice", "Notice")
                        .WithMany("WorkGroups")
                        .HasForeignKey("NoticeID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("Notices")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notice");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkFile", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.WorkFiles.WorkFilesFolder", "WorkFilesFolder")
                        .WithMany("WorkFiles")
                        .HasForeignKey("WorkFilesFolderID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkFilesFolder");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkFilesFolder", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("Folders")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkGroupAlbum", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("Albums")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkPhoto", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.WorkFiles.WorkGroupAlbum", "Album")
                        .WithMany("WorkPhotos")
                        .HasForeignKey("AlbumID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.ListWorkGroup", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", "WorkGroup")
                        .WithMany("WorkLists")
                        .HasForeignKey("WorkGroupID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.WorkLists.WorkList", "WorkList")
                        .WithMany("WorkGroups")
                        .HasForeignKey("WorkListID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroup");

                    b.Navigation("WorkList");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkListExcludedUser", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.WorkLists.WorkList", "WorkList")
                        .WithMany("ExcludedUsers")
                        .HasForeignKey("WorkListID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkList");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkListItem", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "ComplaterUser")
                        .WithMany()
                        .HasForeignKey("ComplaterUserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.WorkLists.WorkList", "WorkList")
                        .WithMany("Items")
                        .HasForeignKey("WorkListID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplaterUser");

                    b.Navigation("WorkList");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkListNotifiedMe", b =>
                {
                    b.HasOne("NoteWith.Domain.EntitiyModels.UserModels.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NoteWith.Domain.EntitiyModels.WorkLists.WorkList", "WorkList")
                        .WithMany("WorkListNotifiedMes")
                        .HasForeignKey("WorkListID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkList");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.EventModels.WorkEvent", b =>
                {
                    b.Navigation("ExcludedUsers");

                    b.Navigation("Groups");

                    b.Navigation("NotifiedMes");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.GroupModels.WorkGroup", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("EventGroups");

                    b.Navigation("Folders");

                    b.Navigation("Messages");

                    b.Navigation("NoteGroups");

                    b.Navigation("Notices");

                    b.Navigation("WorkGroupUsers");

                    b.Navigation("WorkLists");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoteModels.Note", b =>
                {
                    b.Navigation("ExcludedUsers");

                    b.Navigation("NoteGroups");

                    b.Navigation("Notifieds");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.NoticeModels.Notice", b =>
                {
                    b.Navigation("SeenUsers");

                    b.Navigation("WorkGroups");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.UserModels.UserModel", b =>
                {
                    b.Navigation("WorkGroupUsers");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkFilesFolder", b =>
                {
                    b.Navigation("WorkFiles");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkFiles.WorkGroupAlbum", b =>
                {
                    b.Navigation("WorkPhotos");
                });

            modelBuilder.Entity("NoteWith.Domain.EntitiyModels.WorkLists.WorkList", b =>
                {
                    b.Navigation("ExcludedUsers");

                    b.Navigation("Items");

                    b.Navigation("WorkGroups");

                    b.Navigation("WorkListNotifiedMes");
                });
#pragma warning restore 612, 618
        }
    }
}
